version: 2
# .goreleaser.yml
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    id: "git-barcode-sheet"
    package_name: "git-barcode-sheet"
    homepage: "https://github.com/arran4/git-barcode-sheet"
    maintainer: "Arran Ubels <arran@ubels.com.au>"
    description: "chat barcode sheet generator."
    license: "MIT"
    formats:
      - "deb"
      - "rpm"
    bindir: "/usr/bin"
